version: "3.9"
services:
  user:
    image: 'postgres:16'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: user
      PGDATA: "/var/lib/postgresql/data/docker-data/user"
    ports:
      - "5433:5432"